/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.parcial2A;

public class App {  

    public static void main(String[] args) {
      System.out.println("Ejecutando Liquidación Empresa...");
    }
}
